// <auto-generated />
#nullable enable

using PCSLib.Data.DBF;
using PCSLib.Data.DTO;

namespace WebServices.Mapperly
{

	public static partial class LocasystEntityMapper
	{
		public static partial IQueryable<Tiers> ProjectToDto(this IQueryable<LocClt> queryable);
		public static partial Tiers Map(LocClt entity);
		public static partial IQueryable<TiersSite> ProjectToDto(this IQueryable<LocCltAd> queryable);
		public static partial TiersSite Map(LocCltAd entity);
		public static partial IQueryable<Contact> ProjectToDto(this IQueryable<LocPer> queryable);
		public static partial Contact Map(LocPer entity);
		public static partial IQueryable<Codification> ProjectToDto(this IQueryable<LocCode> queryable);
		public static partial Codification Map(LocCode entity);
		public static partial IQueryable<Affaire> ProjectToDto(this IQueryable<LocAff> queryable);
		public static partial Affaire Map(LocAff entity);
		public static partial IQueryable<Location> ProjectToDto(this IQueryable<LocGen> queryable);
		public static partial Location Map(LocGen entity);
		public static partial IQueryable<Facture> ProjectToDto(this IQueryable<FacGen> queryable);
		public static partial Facture Map(FacGen entity);
	}


    public static partial class LocasystEntityMapper
    {
        [global::System.CodeDom.Compiler.GeneratedCode("Riok.Mapperly", "4.3.0.0")]
        public static partial global::System.Linq.IQueryable<global::PCSLib.Data.DTO.Tiers> ProjectToDto(this global::System.Linq.IQueryable<global::PCSLib.Data.DBF.LocClt> queryable)
        {
#nullable disable
            return global::System.Linq.Queryable.Select(
                queryable,
                x => new global::PCSLib.Data.DTO.Tiers()
                {
                    Adresse1 = x.Adresse1,
                    Adresse2 = x.Adresse2,
                    BIC = x.BIC,
                    CodeAdresseFacturation = x.CodeAdresseFacturation,
                    CodeComptableClient = x.CodeComptableClient,
                    CodeComptableFournisseur = x.CodeComptableFournisseur,
                    CodeDelaiReglementClient = x.CodeDelaiReglementClient,
                    CodeDelaiReglementFournisseur = x.CodeDelaiReglementFournisseur,
                    CodeEntete = x.CodeEntete,
                    CodeModeReglementClient = x.CodeModeReglementClient,
                    CodeModeReglementFournisseur = x.CodeModeReglementFournisseur,
                    CodePostal = x.CodePostal,
                    CodeSecteur = x.CodeSecteur,
                    CodeSousSecteur = x.CodeSousSecteur,
                    DelaiReglementClient = x.DelaiReglementClient,
                    DelaiReglementFournisseur = x.DelaiReglementFournisseur,
                    DTCreation = x.DTCreation,
                    DTModification = x.DTModification,
                    Fax = x.Fax,
                    IBAN = x.IBAN,
                    IdClientFournisseur = x.IdClientFournisseur,
                    IdContactPrincipal = x.IdContactPrincipal,
                    IdTiers = x.IdTiers,
                    IdUtilisateurCreation = x.IdUtilisateurCreation,
                    IdUtilisateurModification = x.IdUtilisateurModification,
                    IdUtilisateurSuivi = x.IdUtilisateurSuivi,
                    IsClient = x.IsClient,
                    IsFournisseur = x.IsFournisseur,
                    IsInactifClient = x.IsInactifClient,
                    IsInactifFournisseur = x.IsInactifFournisseur,
                    ModeReglementClient = x.ModeReglementClient,
                    ModeReglementFournisseur = x.ModeReglementFournisseur,
                    Nom = x.Nom,
                    Nom2 = x.Nom2,
                    Pays = x.Pays,
                    Remise1 = x.Remise1,
                    Remise2 = x.Remise2,
                    Remise3 = x.Remise3,
                    Remise4 = x.Remise4,
                    Remise5 = x.Remise5,
                    Remise6 = x.Remise6,
                    RemisePrestation = x.RemisePrestation,
                    RemiseTransport = x.RemiseTransport,
                    RemiseVente = x.RemiseVente,
                    Risque = x.Risque,
                    SIRET = x.SIRET,
                    SiteWeb = x.SiteWeb,
                    Tarif = x.Tarif,
                    Telephone = x.Telephone,
                    TvaIntracommunautaire = x.TvaIntracommunautaire,
                    Ville = x.Ville,
                }
            );
#nullable enable
        }

        [global::System.CodeDom.Compiler.GeneratedCode("Riok.Mapperly", "4.3.0.0")]
        public static partial global::PCSLib.Data.DTO.Tiers Map(global::PCSLib.Data.DBF.LocClt entity)
        {
            var target = new global::PCSLib.Data.DTO.Tiers();
            target.Adresse1 = entity.Adresse1;
            target.Adresse2 = entity.Adresse2;
            target.BIC = entity.BIC;
            target.CodeAdresseFacturation = entity.CodeAdresseFacturation;
            target.CodeComptableClient = entity.CodeComptableClient;
            target.CodeComptableFournisseur = entity.CodeComptableFournisseur;
            target.CodeDelaiReglementClient = entity.CodeDelaiReglementClient;
            target.CodeDelaiReglementFournisseur = entity.CodeDelaiReglementFournisseur;
            target.CodeEntete = entity.CodeEntete;
            target.CodeModeReglementClient = entity.CodeModeReglementClient;
            target.CodeModeReglementFournisseur = entity.CodeModeReglementFournisseur;
            target.CodePostal = entity.CodePostal;
            target.CodeSecteur = entity.CodeSecteur;
            target.CodeSousSecteur = entity.CodeSousSecteur;
            target.DelaiReglementClient = entity.DelaiReglementClient;
            target.DelaiReglementFournisseur = entity.DelaiReglementFournisseur;
            target.DTCreation = entity.DTCreation;
            target.DTModification = entity.DTModification;
            target.Fax = entity.Fax;
            target.IBAN = entity.IBAN;
            target.IdClientFournisseur = entity.IdClientFournisseur;
            target.IdContactPrincipal = entity.IdContactPrincipal;
            target.IdTiers = entity.IdTiers;
            target.IdUtilisateurCreation = entity.IdUtilisateurCreation;
            target.IdUtilisateurModification = entity.IdUtilisateurModification;
            target.IdUtilisateurSuivi = entity.IdUtilisateurSuivi;
            target.IsClient = entity.IsClient;
            target.IsFournisseur = entity.IsFournisseur;
            target.IsInactifClient = entity.IsInactifClient;
            target.IsInactifFournisseur = entity.IsInactifFournisseur;
            target.ModeReglementClient = entity.ModeReglementClient;
            target.ModeReglementFournisseur = entity.ModeReglementFournisseur;
            target.Nom = entity.Nom;
            target.Nom2 = entity.Nom2;
            target.Pays = entity.Pays;
            target.Remise1 = entity.Remise1;
            target.Remise2 = entity.Remise2;
            target.Remise3 = entity.Remise3;
            target.Remise4 = entity.Remise4;
            target.Remise5 = entity.Remise5;
            target.Remise6 = entity.Remise6;
            target.RemisePrestation = entity.RemisePrestation;
            target.RemiseTransport = entity.RemiseTransport;
            target.RemiseVente = entity.RemiseVente;
            target.Risque = entity.Risque;
            target.SIRET = entity.SIRET;
            target.SiteWeb = entity.SiteWeb;
            target.Tarif = entity.Tarif;
            target.Telephone = entity.Telephone;
            target.TvaIntracommunautaire = entity.TvaIntracommunautaire;
            target.Ville = entity.Ville;
            return target;
        }

        [global::System.CodeDom.Compiler.GeneratedCode("Riok.Mapperly", "4.3.0.0")]
        public static partial global::System.Linq.IQueryable<global::PCSLib.Data.DTO.TiersSite> ProjectToDto(this global::System.Linq.IQueryable<global::PCSLib.Data.DBF.LocCltAd> queryable)
        {
#nullable disable
            return global::System.Linq.Queryable.Select(
                queryable,
                x => new global::PCSLib.Data.DTO.TiersSite()
                {
                    IdTiers = x.IdTiers,
                    IdTiersSite = x.IdTiersSite,
                    LibelleAdresse = x.LibelleAdresse,
                }
            );
#nullable enable
        }

        [global::System.CodeDom.Compiler.GeneratedCode("Riok.Mapperly", "4.3.0.0")]
        public static partial global::PCSLib.Data.DTO.TiersSite Map(global::PCSLib.Data.DBF.LocCltAd entity)
        {
            var target = new global::PCSLib.Data.DTO.TiersSite();
            target.IdTiers = entity.IdTiers;
            target.IdTiersSite = entity.IdTiersSite;
            target.LibelleAdresse = entity.LibelleAdresse;
            return target;
        }

        [global::System.CodeDom.Compiler.GeneratedCode("Riok.Mapperly", "4.3.0.0")]
        public static partial global::System.Linq.IQueryable<global::PCSLib.Data.DTO.Contact> ProjectToDto(this global::System.Linq.IQueryable<global::PCSLib.Data.DBF.LocPer> queryable)
        {
#nullable disable
            return global::System.Linq.Queryable.Select(
                queryable,
                x => new global::PCSLib.Data.DTO.Contact()
                {
                    CodeCivilite = x.CodeCivilite,
                    CodeFonction = x.CodeFonction,
                    DTCreation = x.DTCreation,
                    DTModification = x.DTModification,
                    Email = x.Email,
                    Email2 = x.Email2,
                    Email3 = x.Email3,
                    Email4 = x.Email4,
                    FAX = x.FAX,
                    IdContact = x.IdContact,
                    IdTiers = x.IdTiers,
                    IdTiersSite = x.IdTiersSite,
                    IdUtilisateurCreation = x.IdUtilisateurCreation,
                    IdUtilisateurModification = x.IdUtilisateurModification,
                    IsInactif = x.IsInactif,
                    Mobile = x.Mobile,
                    Nom = x.Nom,
                    Observations = x.Observations,
                    Prenom = x.Prenom,
                    Telephone = x.Telephone,
                    Titre = x.Titre,
                }
            );
#nullable enable
        }

        [global::System.CodeDom.Compiler.GeneratedCode("Riok.Mapperly", "4.3.0.0")]
        public static partial global::PCSLib.Data.DTO.Contact Map(global::PCSLib.Data.DBF.LocPer entity)
        {
            var target = new global::PCSLib.Data.DTO.Contact();
            target.CodeCivilite = entity.CodeCivilite;
            target.CodeFonction = entity.CodeFonction;
            target.DTCreation = entity.DTCreation;
            target.DTModification = entity.DTModification;
            target.Email = entity.Email;
            target.Email2 = entity.Email2;
            target.Email3 = entity.Email3;
            target.Email4 = entity.Email4;
            target.FAX = entity.FAX;
            target.IdContact = entity.IdContact;
            target.IdTiers = entity.IdTiers;
            target.IdTiersSite = entity.IdTiersSite;
            target.IdUtilisateurCreation = entity.IdUtilisateurCreation;
            target.IdUtilisateurModification = entity.IdUtilisateurModification;
            target.IsInactif = entity.IsInactif;
            target.Mobile = entity.Mobile;
            target.Nom = entity.Nom;
            target.Observations = entity.Observations;
            target.Prenom = entity.Prenom;
            target.Telephone = entity.Telephone;
            target.Titre = entity.Titre;
            return target;
        }

        [global::System.CodeDom.Compiler.GeneratedCode("Riok.Mapperly", "4.3.0.0")]
        public static partial global::System.Linq.IQueryable<global::PCSLib.Data.DTO.Codification> ProjectToDto(this global::System.Linq.IQueryable<global::PCSLib.Data.DBF.LocCode> queryable)
        {
#nullable disable
            return global::System.Linq.Queryable.Select(
                queryable,
                x => new global::PCSLib.Data.DTO.Codification()
                {
                    Code = x.Code,
                    Libelle = x.Libelle,
                    NIVEAU = x.NIVEAU,
                    Observations = x.Observations,
                    SousCode = x.SousCode,
                    Type = x.Type,
                }
            );
#nullable enable
        }

        [global::System.CodeDom.Compiler.GeneratedCode("Riok.Mapperly", "4.3.0.0")]
        public static partial global::PCSLib.Data.DTO.Codification Map(global::PCSLib.Data.DBF.LocCode entity)
        {
            var target = new global::PCSLib.Data.DTO.Codification();
            target.Code = entity.Code;
            target.Libelle = entity.Libelle;
            target.NIVEAU = entity.NIVEAU;
            target.Observations = entity.Observations;
            target.SousCode = entity.SousCode;
            target.Type = entity.Type;
            return target;
        }

        [global::System.CodeDom.Compiler.GeneratedCode("Riok.Mapperly", "4.3.0.0")]
        public static partial global::System.Linq.IQueryable<global::PCSLib.Data.DTO.Affaire> ProjectToDto(this global::System.Linq.IQueryable<global::PCSLib.Data.DBF.LocAff> queryable)
        {
#nullable disable
            return global::System.Linq.Queryable.Select(
                queryable,
                x => new global::PCSLib.Data.DTO.Affaire()
                {
                    CodeTypeAffaire = x.CodeTypeAffaire,
                    DateCreation = x.DateCreation,
                    DateDebut = x.DateDebut,
                    DateFin = x.DateFin,
                    DateModification = x.DateModification,
                    IdAffaire = x.IdAffaire,
                    IdUtilisateurCreation = x.IdUtilisateurCreation,
                    IdUtilisateurModification = x.IdUtilisateurModification,
                    IdUtilisateurSuivi = x.IdUtilisateurSuivi,
                    NumAffaire = x.NumAffaire,
                    Observations = x.Observations,
                    SUBVENTION = x.SUBVENTION,
                }
            );
#nullable enable
        }

        [global::System.CodeDom.Compiler.GeneratedCode("Riok.Mapperly", "4.3.0.0")]
        public static partial global::PCSLib.Data.DTO.Affaire Map(global::PCSLib.Data.DBF.LocAff entity)
        {
            var target = new global::PCSLib.Data.DTO.Affaire();
            target.CodeTypeAffaire = entity.CodeTypeAffaire;
            target.DateCreation = entity.DateCreation;
            target.DateDebut = entity.DateDebut;
            target.DateFin = entity.DateFin;
            target.DateModification = entity.DateModification;
            target.IdAffaire = entity.IdAffaire;
            target.IdUtilisateurCreation = entity.IdUtilisateurCreation;
            target.IdUtilisateurModification = entity.IdUtilisateurModification;
            target.IdUtilisateurSuivi = entity.IdUtilisateurSuivi;
            target.NumAffaire = entity.NumAffaire;
            target.Observations = entity.Observations;
            target.SUBVENTION = entity.SUBVENTION;
            return target;
        }

        [global::System.CodeDom.Compiler.GeneratedCode("Riok.Mapperly", "4.3.0.0")]
        public static partial global::System.Linq.IQueryable<global::PCSLib.Data.DTO.Location> ProjectToDto(this global::System.Linq.IQueryable<global::PCSLib.Data.DBF.LocGen> queryable)
        {
#nullable disable
            return global::System.Linq.Queryable.Select(
                queryable,
                x => new global::PCSLib.Data.DTO.Location()
                {
                    CodeDelaiReglement = x.CodeDelaiReglement,
                    CodeModeReglement = x.CodeModeReglement,
                    CodeResultatDevis = x.CodeResultatDevis,
                    DateFacturation = x.DateFacturation,
                    DelaiReglement = x.DelaiReglement,
                    DTCreation = x.DTCreation,
                    DTDebutDemontage = x.DTDebutDemontage,
                    DTDebutMontage = x.DTDebutMontage,
                    DTDebutPreparation = x.DTDebutPreparation,
                    DTDebutPrestation = x.DTDebutPrestation,
                    DTDepartMateriel = x.DTDepartMateriel,
                    DTFinDemontage = x.DTFinDemontage,
                    DTFinMontage = x.DTFinMontage,
                    DTFinPreparation = x.DTFinPreparation,
                    DTFinPrestation = x.DTFinPrestation,
                    DTModification = x.DTModification,
                    DTRetourMateriel = x.DTRetourMateriel,
                    ForfaitLocation = x.ForfaitLocation,
                    ForfaitPrestation = x.ForfaitPrestation,
                    ForfaitTransport = x.ForfaitTransport,
                    HasPrestation = x.HasPrestation,
                    HasTransport = x.HasTransport,
                    IdAffaire = x.IdAffaire,
                    IdContact1 = x.IdContact1,
                    IdContact2 = x.IdContact2,
                    IdTiers = x.IdTiers,
                    IdUtilisateurCreation = x.IdUtilisateurCreation,
                    IdUtilisateurModification = x.IdUtilisateurModification,
                    IdUtilisateurSuivi = x.IdUtilisateurSuivi,
                    IdUtilisateurSuiviPreparation = x.IdUtilisateurSuiviPreparation,
                    IdUtilisateurSuiviTechnique = x.IdUtilisateurSuiviTechnique,
                    ModeReglement = x.ModeReglement,
                    NumeroLocation = x.NumeroLocation,
                    ReferenceClient = x.ReferenceClient,
                    ReferenceInterne = x.ReferenceInterne,
                    STATUT = x.STATUT,
                    StatutPreparation = x.StatutPreparation,
                    TOTALHT = x.TOTALHT,
                    TypeLocation = x.TypeLocation,
                }
            );
#nullable enable
        }

        [global::System.CodeDom.Compiler.GeneratedCode("Riok.Mapperly", "4.3.0.0")]
        public static partial global::PCSLib.Data.DTO.Location Map(global::PCSLib.Data.DBF.LocGen entity)
        {
            var target = new global::PCSLib.Data.DTO.Location();
            target.CodeDelaiReglement = entity.CodeDelaiReglement;
            target.CodeModeReglement = entity.CodeModeReglement;
            target.CodeResultatDevis = entity.CodeResultatDevis;
            target.DateFacturation = entity.DateFacturation;
            target.DelaiReglement = entity.DelaiReglement;
            target.DTCreation = entity.DTCreation;
            target.DTDebutDemontage = entity.DTDebutDemontage;
            target.DTDebutMontage = entity.DTDebutMontage;
            target.DTDebutPreparation = entity.DTDebutPreparation;
            target.DTDebutPrestation = entity.DTDebutPrestation;
            target.DTDepartMateriel = entity.DTDepartMateriel;
            target.DTFinDemontage = entity.DTFinDemontage;
            target.DTFinMontage = entity.DTFinMontage;
            target.DTFinPreparation = entity.DTFinPreparation;
            target.DTFinPrestation = entity.DTFinPrestation;
            target.DTModification = entity.DTModification;
            target.DTRetourMateriel = entity.DTRetourMateriel;
            target.ForfaitLocation = entity.ForfaitLocation;
            target.ForfaitPrestation = entity.ForfaitPrestation;
            target.ForfaitTransport = entity.ForfaitTransport;
            target.HasPrestation = entity.HasPrestation;
            target.HasTransport = entity.HasTransport;
            target.IdAffaire = entity.IdAffaire;
            target.IdContact1 = entity.IdContact1;
            target.IdContact2 = entity.IdContact2;
            target.IdTiers = entity.IdTiers;
            target.IdUtilisateurCreation = entity.IdUtilisateurCreation;
            target.IdUtilisateurModification = entity.IdUtilisateurModification;
            target.IdUtilisateurSuivi = entity.IdUtilisateurSuivi;
            target.IdUtilisateurSuiviPreparation = entity.IdUtilisateurSuiviPreparation;
            target.IdUtilisateurSuiviTechnique = entity.IdUtilisateurSuiviTechnique;
            target.ModeReglement = entity.ModeReglement;
            target.NumeroLocation = entity.NumeroLocation;
            target.ReferenceClient = entity.ReferenceClient;
            target.ReferenceInterne = entity.ReferenceInterne;
            target.STATUT = entity.STATUT;
            target.StatutPreparation = entity.StatutPreparation;
            target.TOTALHT = entity.TOTALHT;
            target.TypeLocation = entity.TypeLocation;
            return target;
        }

        [global::System.CodeDom.Compiler.GeneratedCode("Riok.Mapperly", "4.3.0.0")]
        public static partial global::System.Linq.IQueryable<global::PCSLib.Data.DTO.Facture> ProjectToDto(this global::System.Linq.IQueryable<global::PCSLib.Data.DBF.FacGen> queryable)
        {
#nullable disable
            return global::System.Linq.Queryable.Select(
                queryable,
                x => new global::PCSLib.Data.DTO.Facture()
                {
                    CodeDelaiReglement = x.CodeDelaiReglement,
                    CodeModeReglement = x.CodeModeReglement,
                    DateFacture = x.DateFacture,
                    DateReglement = x.DateReglement,
                    Devise = x.Devise,
                    DTCreation = x.DTCreation,
                    DTExportCompable = x.DTExportCompable,
                    DTLivraison = x.DTLivraison,
                    DTModification = x.DTModification,
                    IdAffaire = x.IdAffaire,
                    IdContact1 = x.IdContact1,
                    IdContact2 = x.IdContact2,
                    IdTiers = x.IdTiers,
                    IdUtilisateurCreation = x.IdUtilisateurCreation,
                    IdUtilisateurModification = x.IdUtilisateurModification,
                    NumeroFacture = x.NumeroFacture,
                    ReferenceClient = x.ReferenceClient,
                    ReferenceCommande = x.ReferenceCommande,
                    ReferenceFacture = x.ReferenceFacture,
                    TotalHT = x.TotalHT,
                    TotalTTC = x.TotalTTC,
                }
            );
#nullable enable
        }

        [global::System.CodeDom.Compiler.GeneratedCode("Riok.Mapperly", "4.3.0.0")]
        public static partial global::PCSLib.Data.DTO.Facture Map(global::PCSLib.Data.DBF.FacGen entity)
        {
            var target = new global::PCSLib.Data.DTO.Facture();
            target.CodeDelaiReglement = entity.CodeDelaiReglement;
            target.CodeModeReglement = entity.CodeModeReglement;
            target.DateFacture = entity.DateFacture;
            target.DateReglement = entity.DateReglement;
            target.Devise = entity.Devise;
            target.DTCreation = entity.DTCreation;
            target.DTExportCompable = entity.DTExportCompable;
            target.DTLivraison = entity.DTLivraison;
            target.DTModification = entity.DTModification;
            target.IdAffaire = entity.IdAffaire;
            target.IdContact1 = entity.IdContact1;
            target.IdContact2 = entity.IdContact2;
            target.IdTiers = entity.IdTiers;
            target.IdUtilisateurCreation = entity.IdUtilisateurCreation;
            target.IdUtilisateurModification = entity.IdUtilisateurModification;
            target.NumeroFacture = entity.NumeroFacture;
            target.ReferenceClient = entity.ReferenceClient;
            target.ReferenceCommande = entity.ReferenceCommande;
            target.ReferenceFacture = entity.ReferenceFacture;
            target.TotalHT = entity.TotalHT;
            target.TotalTTC = entity.TotalTTC;
            return target;
        }
    }
}